services:
  senryu-app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .dockervenv:/app/.venv
      - .:/app
    ports:
      - 8888:8888

  db:
      build:
        context: .
        dockerfile: Dockerfile.mysql
      platform: linux/x86_64
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
        MYSQL_DATABASE: 'senryu'  # 初期データベースとしてdemoを設定
        TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
      volumes:
        - mysql_data:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - 33306:3306  # ホストマシンのポート33306を、docker内のポート3306に接続する
volumes:
  mysql_data: